server:
  port: 8005
spring:
  application:
    name: "employee-microservice"
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:mem:employee-db
    driverClassName: org.h2.Driver
    username: admin
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
