server:
  port: 8001
spring:
  sql:
    init:
      mode: always
  application:
    name: "employee-microservice"
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:mem:employee-db
    driverClassName: org.h2.Driver
    username: admin
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
