server:
  port: 8003
spring:
  application:
    name: "leave"
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:mem:qadb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto: update
  h2:
    console:
      enabled: true
